Only base64 decode the part that is base64
Older b64decode just ignored the trailing garage but in python
3.14.4 it changed to strict_mode=validate which made this part
throw binascii.Error: Incorrect padding

PoC:
```
$ cat SHA256.sig
untrusted comment: verify with impex_2021.pub
RWSqKOPSP+TC/tcpBY7ivdyImpqQW8Lusc8bp5GYj1zFC3gJYIyRZxzfpA0DjYubanYeeq41AcCztgL7JFiNWTXRJSdYznllGwo=
SHA256 (run.sh) = 36d4ec5712bc64eee8f4f387599245f839690c179179fd4efd450fcc27462d46
SHA256 (impex-watchdog.sh) = b90a4b53c86010bd64fc9d25f906c6739c7e15f4188ab689e9941727ce16d90a
$ python --version
Python 3.13.12
$ python -c 'import base64;f=open("./SHA256.sig").read();b=base64.b64decode(f.split("\n",1)[1]); print(len(b))'
74
$

Newer python:

$ python --version
Python 3.14.4
$ python -c 'import base64;f=open("./SHA256.sig").read();b=base64.b64decode(f.split("\n",1)[1]); print(len(b))'
Traceback (most recent call last):
  File "<string>", line 1, in <module>
    import base64;f=open("./SHA256.sig").read();b=base64.b64decode(f.split("\n",1)[1]); print(len(b))
                                                  ~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib64/python3.14/base64.py", line 85, in b64decode
    return binascii.a2b_base64(s, strict_mode=validate)
           ~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^
binascii.Error: Incorrect padding
$
```