signi.py: checkfiles expects a string, not a bytes-like object
This matches what is done here: https://github.com/bjornedstrom/python-signify/blob/master/signify/pure.py#L440

before:
```
Signature Verified
Traceback (most recent call last):
  File "/usr/bin/signi.py", line 181, in <module>
    main()
  File "/usr/bin/signi.py", line 121, in main
    for path, status in check.checkfiles(os.getcwd(), message):
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/site-packages/signify/check.py", line 36, in checkfiles
    for algo, path, ref_digest in re.findall(
                                  ^^^^^^^^^^^
  File "/usr/lib64/python3.12/re/__init__.py", line 217, in findall
    return _compile(pattern, flags).findall(string)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: cannot use a string pattern on a bytes-like object
```

after:
```
Signature Verified
foo.pem: OK
bar.pem: OK
```